# Generated by Django 3.2.4 on 2021-10-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.FileField(blank=True, upload_to='img_autor/'),
        ),
    ]
